# Overrides for development

volumes:
  pgdata:

services:
  kablo:
    build:
      target: dev
    # Runserver for live reload
    command: "python3 manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/kablo
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${DJANGO_DOCKER_PORT}:9000"

  postgres:
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER:?}
      POSTGRES_PASSWORD: ${PGPASSWORD:?}
      POSTGRES_DB: ${PGDATABASE:?}
    ports:
      - ${POSTGRES_DOCKER_PORT:?}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:?}"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
