# Generated by Django 5.0.2 on 2024-02-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tube',
            old_name='networkSegments',
            new_name='track_sections',
        ),
        migrations.AlterField(
            model_name='tracktracksection',
            name='index',
            field=models.IntegerField(default=1),
        ),
    ]
