# Generated by Django 5.0.3 on 2024-04-02 10:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableTensionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.PositiveIntegerField(null=True)),
                ('original_uuid', models.UUIDField(null=True)),
                ('code', models.PositiveIntegerField(null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64)),
                ('index', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.PositiveIntegerField(null=True)),
                ('original_uuid', models.UUIDField(null=True)),
                ('code', models.PositiveIntegerField(null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64)),
                ('index', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TubeCableProtectionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_id', models.PositiveIntegerField(null=True)),
                ('original_uuid', models.UUIDField(null=True)),
                ('code', models.PositiveIntegerField(null=True)),
                ('name_fr', models.CharField(blank=True, max_length=64)),
                ('index', models.PositiveIntegerField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cable',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=2056),
        ),
        migrations.AddField(
            model_name='station',
            name='label',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tube',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=2056),
        ),
        migrations.AddField(
            model_name='cable',
            name='tension',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.cabletensiontype'),
        ),
        migrations.AddField(
            model_name='cable',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.statustype'),
        ),
        migrations.AddField(
            model_name='tube',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.statustype'),
        ),
        migrations.AddField(
            model_name='tube',
            name='cable_protection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.tubecableprotectiontype'),
        ),
    ]
