# Generated by Django 5.0.3 on 2024-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="identifier",
            field=models.TextField(blank=True, null=True),
        ),
    ]
