# Generated by Django 5.0.3 on 2024-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='original_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='original_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='original_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='tube',
            name='original_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
