# Generated by Django 5.0.3 on 2024-04-03 07:48

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_remove_cable_model"),
        ("valuelist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_uuid", models.UUIDField(null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        null=True, srid=2056
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="valuelist.statustype",
                    ),
                ),
                (
                    "tension",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="valuelist.cabletensiontype",
                    ),
                ),
                ("tubes", models.ManyToManyField(to="network.tube")),
            ],
        ),
    ]
