# Generated by Django 5.0.3 on 2024-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_new_cable_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cable",
            name="tubes",
        ),
        migrations.AddField(
            model_name="tube",
            name="cables",
            field=models.ManyToManyField(to="network.cable"),
        ),
    ]
