name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
    - uses: actions/checkout@v4

    - name: Create env
      run: cp .env.example .env

    - name: Load .env file
      uses: xom9ikk/dotenv@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Django image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: kablo/.docker/Dockerfile
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: kablo/kablo:latest

    - name: Setup Compose
      run: |
        # start the stack
        docker compose up --build -d

    - name: Check migrations
      run: docker compose exec kablo python manage.py makemigrations --check

    - name: Migrate and populate
      run: |
        docker compose exec kablo python manage.py collectstatic --no-input
        docker compose exec kablo python manage.py migrate --no-input
        docker compose exec kablo python manage.py populate_users
        docker compose exec kablo python manage.py populate_valuelists

    - name: Run unit tests
      run: docker compose exec kablo python manage.py test

#    - name: Run integration tests
#      run: docker compose run integration_tests

    - name: Failure logs
      if: failure()
      run: docker-compose logs
